//! Native rendering of the production addon's exported finale events. See sample-songs/README.md.
//! Explicit opt-in because the fixtures are generated by Vitest and renders are audio artifacts.
use entropy_engine::{
    audio::{
        self,
        character::{CharacterKind, CharacterParams, TrackBusRender},
    },
    deno::{
        addon_ops::{NoteEventConfig, TrackBusRenderConfig},
        brass_ops::BrassNoteConfig,
        matter_ops::MatterHitConfig,
        physmod_ops::PhysModNoteConfig,
        wavetable_ops::WavetableNoteConfig,
    },
};
use serde::{de::DeserializeOwned, Deserialize};
use serde_json::Value;
use std::{fs, path::PathBuf};

// Select a four-bar finale from the actual export payload and move it to time zero.
fn excerpt<T: DeserializeOwned>(v: &Value, key: &str, start: f64, end: f64) -> Vec<T> {
    v[key]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|e| {
            let at = e["startTime"].as_f64().unwrap();
            if at < start - 1e-7 || at >= end - 1e-7 {
                return None;
            }
            let mut e = e.clone();
            e["startTime"] = (at - start).max(0.0).into();
            Some(serde_json::from_value(e).unwrap())
        })
        .collect()
}

#[derive(Deserialize)]
struct Table {
    id: String,
    preset: String,
}

#[test]
#[ignore = "generate production export fixtures with ENTROPY_SHOWCASE_FIXTURES first"]
fn showcase_finales_render_with_headroom() {
    let folder = PathBuf::from(std::env::var("ENTROPY_SHOWCASE_FIXTURES").expect("fixture folder"));
    for bpm in [144, 108, 118, 106, 124] {
        let v: Value =
            serde_json::from_slice(&fs::read(folder.join(format!("{bpm}.json"))).unwrap()).unwrap();
        let tables: Vec<Table> = serde_json::from_value(v["tables"].clone()).unwrap();
        for t in &tables {
            let shared = audio::wavetable::ensure_table(&t.id);
            assert!(audio::wavetable::lock_table(&shared).load_preset(&t.preset));
        }
        let bar = 240.0 / bpm as f64;
        let notes: Vec<NoteEventConfig> = excerpt(&v, "notes", 48.0 * bar, 52.0 * bar);
        let wt: Vec<WavetableNoteConfig> = excerpt(&v, "wavetable", 48.0 * bar, 52.0 * bar);
        let pm: Vec<PhysModNoteConfig> = excerpt(&v, "physmod", 48.0 * bar, 52.0 * bar);
        let brass: Vec<BrassNoteConfig> = excerpt(&v, "brass", 48.0 * bar, 52.0 * bar);
        let matter: Vec<MatterHitConfig> = excerpt(&v, "matter", 48.0 * bar, 52.0 * bar);
        let configs: Vec<TrackBusRenderConfig> =
            serde_json::from_value(v["buses"].clone()).unwrap();
        let buses: Vec<_> = configs
            .iter()
            .map(|b| TrackBusRender {
                gain: b.gain as f32,
                silences: vec![],
                effects: b
                    .effects
                    .iter()
                    .map(|e| CharacterParams {
                        kind: CharacterKind::parse(&e.kind).unwrap(),
                        amount: e.amount as f32,
                        pattern: e.pattern,
                        bpm: e.bpm,
                        beat: Some(0.0),
                    })
                    .collect(),
            })
            .collect();
        let route = |id: &Option<String>| {
            Some(
                configs
                    .iter()
                    .position(|b| Some(&b.track) == id.as_ref())
                    .expect("routed track"),
            )
        };
        let nr: Vec<_> = notes.iter().map(|e| route(&e.track)).collect();
        let wr: Vec<_> = wt.iter().map(|e| route(&e.track_id)).collect();
        let pr: Vec<_> = pm.iter().map(|e| route(&e.track_id)).collect();
        let br: Vec<_> = brass.iter().map(|e| route(&e.track_id)).collect();
        let mr: Vec<_> = matter.iter().map(|e| route(&e.track_id)).collect();
        let notes: Vec<_> = notes
            .into_iter()
            .map(|e| audio::NoteEvent {
                start_time: e.start_time,
                voice: e.waveform,
                params: audio::NoteParams {
                    freq: e.freq,
                    duration: e.duration,
                    cutoff: e.cutoff,
                    resonance: e.resonance,
                    gain: e.gain,
                    attack: e.attack,
                    decay: e.decay,
                    sustain: e.sustain,
                    release: e.release,
                    delay_time: e.delay_time,
                    delay_feedback: e.delay_feedback,
                    delay_mix: e.delay_mix,
                    reverb_room_size: e.reverb_room_size,
                    reverb_time: e.reverb_time,
                    reverb_damping: e.reverb_damping,
                    reverb_mix: e.reverb_mix,
                    filter_env: e.filter_env,
                    filter_decay: e.filter_decay,
                    drive: e.drive,
                },
            })
            .collect();
        let routing = audio::MixRouting {
            buses: &buses,
            notes: &nr,
            wavetable: &wr,
            physmod: &pr,
            brass: &br,
            matter: &mr,
            ..Default::default()
        };
        let path = folder.join(format!("{bpm}-finale.wav"));
        let (duration, warnings) = audio::render_mix_to_wav(
            &notes,
            &[],
            &wt.iter().map(|e| e.to_event()).collect::<Vec<_>>(),
            &pm.iter().map(|e| e.to_event()).collect::<Vec<_>>(),
            &brass.iter().map(|e| e.to_event()).collect::<Vec<_>>(),
            &matter
                .iter()
                .map(|e| e.to_event().unwrap())
                .collect::<Vec<_>>(),
            &[],
            &routing,
            44100,
            &path,
        )
        .unwrap();
        assert!(warnings.is_empty());
        assert!(duration >= 3.5 * bar);
        let mut wav = hound::WavReader::open(&path).unwrap();
        assert_eq!(wav.spec().channels, 2);
        let samples: Vec<_> = wav
            .samples::<i16>()
            .map(Result::unwrap)
            .map(|s| s as f64 / 32768.0)
            .collect();
        let peak = samples.iter().map(|s| s.abs()).fold(0.0, f64::max);
        let rms = (samples.iter().map(|s| s * s).sum::<f64>() / samples.len() as f64).sqrt();
        println!(
            "{bpm} BPM: {duration:.2}s, peak {:.2} dBFS, RMS {:.2} dBFS: {}",
            20.0 * peak.log10(),
            20.0 * rms.log10(),
            path.display()
        );
        assert!(rms > 0.005, "silent/inaudible finale: {bpm}");
        // The exporter normalizes overloaded mixes to 0.98; stay well below that too.
        assert!(peak < 0.95, "finale needs more headroom: {bpm} peak {peak}");
        for t in tables {
            audio::wavetable::remove_table(&t.id);
        }
    }
}
