//! Native rendering of the Film scores sample songs, whole, from the production addon's export
//! payload. See sample-songs/README.md. Explicit opt-in: the fixtures are generated by Vitest
//! (`ENTROPY_FILM_SCORE_FIXTURES`) and the renders are audio files, minutes of physical modeling.
use entropy_engine::{
    audio::{
        self,
        character::{CharacterKind, CharacterParams, TrackBusRender},
    },
    deno::{
        addon_ops::TrackBusRenderConfig, brass_ops::BrassNoteConfig, matter_ops::MatterHitConfig,
        physmod_ops::PhysModNoteConfig, water_ops::WaterNoteConfig,
    },
};
use serde::de::DeserializeOwned;
use serde_json::Value;
use std::{fs, path::PathBuf};

fn events<T: DeserializeOwned>(v: &Value, key: &str) -> Vec<T> {
    serde_json::from_value(v[key].clone()).unwrap()
}

#[test]
#[ignore = "generate production export fixtures with ENTROPY_FILM_SCORE_FIXTURES first"]
fn film_scores_render_whole_with_headroom() {
    let folder = PathBuf::from(std::env::var("ENTROPY_FILM_SCORE_FIXTURES").expect("fixture folder"));
    // Folded City, Tidewater Signal, Ashen Crown, Rooftop Pursuit, Lanterns Over the Sound.
    for bpm in [64, 66, 92, 140, 76] {
        let v: Value =
            serde_json::from_slice(&fs::read(folder.join(format!("{bpm}.json"))).unwrap()).unwrap();
        let pm: Vec<PhysModNoteConfig> = events(&v, "physmod");
        let brass: Vec<BrassNoteConfig> = events(&v, "brass");
        let matter: Vec<MatterHitConfig> = events(&v, "matter");
        let water: Vec<WaterNoteConfig> = events(&v, "water");
        let configs: Vec<TrackBusRenderConfig> = events(&v, "buses");
        let buses: Vec<_> = configs
            .iter()
            .map(|b| TrackBusRender {
                gain: b.gain as f32,
                eq: None,
                // The saved hard cuts: the whole orchestra stops, reverb tails and all.
                silences: b.silences.iter().map(|s| (s[0], s[1])).collect(),
                effects: b
                    .effects
                    .iter()
                    .map(|e| CharacterParams {
                        kind: CharacterKind::parse(&e.kind).unwrap(),
                        amount: e.amount as f32,
                        pattern: e.pattern,
                        bpm: e.bpm,
                        beat: Some(0.0),
                    })
                    .collect(),
            })
            .collect();
        let route = |id: &Option<String>| {
            Some(configs.iter().position(|b| Some(&b.track) == id.as_ref()).expect("routed track"))
        };
        let pr: Vec<_> = pm.iter().map(|e| route(&e.track_id)).collect();
        let br: Vec<_> = brass.iter().map(|e| route(&e.track_id)).collect();
        let mr: Vec<_> = matter.iter().map(|e| route(&e.track_id)).collect();
        let wr: Vec<_> = water.iter().map(|e| route(&e.track_id)).collect();
        let routing = audio::MixRouting {
            buses: &buses,
            physmod: &pr,
            brass: &br,
            matter: &mr,
            water: &wr,
            ..Default::default()
        };
        let slug = v["slug"].as_str().unwrap();
        let path = folder.join(format!("{slug}.wav"));
        let (duration, warnings) = audio::render_mix_to_wav(
            &[],
            &[],
            &[],
            &pm.iter().map(|e| e.to_event()).collect::<Vec<_>>(),
            &brass.iter().map(|e| e.to_event()).collect::<Vec<_>>(),
            &matter.iter().map(|e| e.to_event().unwrap()).collect::<Vec<_>>(),
            &water.iter().map(|e| e.to_event().unwrap()).collect::<Vec<_>>(),
            &[],
            &routing,
            44100,
            &path,
        )
        .unwrap();
        assert!(warnings.is_empty(), "{warnings:?}");
        let length = v["bars"].as_f64().unwrap() * 240.0 / bpm as f64;
        assert!(duration >= length - 0.5, "{slug}: {duration}s of {length}s");
        let mut wav = hound::WavReader::open(&path).unwrap();
        assert_eq!(wav.spec().channels, 2);
        let samples: Vec<_> = wav
            .samples::<i16>()
            .map(Result::unwrap)
            .map(|s| s as f64 / 32768.0)
            .collect();
        let peak = samples.iter().map(|s| s.abs()).fold(0.0, f64::max);
        let rms = (samples.iter().map(|s| s * s).sum::<f64>() / samples.len() as f64).sqrt();
        // Loudness over time in 4-bar windows: the arc of the cue.
        let window = (44100.0 * 2.0 * 960.0 / bpm as f64) as usize;
        let arc: Vec<_> = samples
            .chunks(window)
            .map(|c| format!("{:.0}", 20.0 * ((c.iter().map(|s| s * s).sum::<f64>() / c.len() as f64).sqrt().max(1e-6)).log10()))
            .collect();
        println!(
            "{slug} ({bpm} BPM): {duration:.1}s, peak {:.2} dBFS, RMS {:.2} dBFS, 4-bar RMS [{}]: {}",
            20.0 * peak.log10(),
            20.0 * rms.log10(),
            arc.join(" "),
            path.display()
        );
        assert!(rms > 0.005, "silent/inaudible: {slug}");
        // The exporter normalizes overloaded mixes to 0.98; stay well below that.
        assert!(peak < 0.95, "{slug} needs more headroom: peak {peak}");
    }
}
