//! Phosphor icons as ordinary characters.
//!
//! Phosphor ships each weight as its own font, and every weight puts an icon at the same
//! private-use codepoint. To let one string say which weight it wants (and so work in every
//! widget, from Rust or from an addon, with no widget option), the three embedded weights live
//! in three separate private-use ranges:
//!
//! - Regular: the font's own codepoint, U+E000 to U+EE82.
//! - Bold: `BOLD_BASE` + (codepoint - U+E000), in supplementary private-use plane 15.
//! - Fill: `FILL_BASE` + (codepoint - U+E000), in supplementary private-use plane 16.
//!
//! `text_layout::shape_text` picks the face from the range and maps the character back to the
//! font's own codepoint before laying it out. Light and Thin are in `src/fonts/phosphor/` but
//! are not embedded.
//!
//! Icon names are Phosphor's own kebab-case names ("play", "arrow-counter-clockwise").
//! `icon_table.rs` is generated by `src/fonts/phosphor/gen_icons.py`.

use crate::entropy_gui::icon_table::ICON_TABLE;

/// First codepoint of the font's private-use block; ranges below are offsets from it.
pub const PUA_BASE: u32 = 0xE000;
/// Offsets past this are outside anything Phosphor draws (highest icon is U+EE82).
const RANGE_LEN: u32 = 0x1900;
pub const BOLD_BASE: u32 = 0xF0000;
pub const FILL_BASE: u32 = 0x10_0000;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum IconStyle {
    Regular,
    Bold,
    Fill,
}

impl IconStyle {
    pub const ALL: [IconStyle; 3] = [IconStyle::Regular, IconStyle::Bold, IconStyle::Fill];

    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "regular" => Some(IconStyle::Regular),
            "bold" => Some(IconStyle::Bold),
            "fill" => Some(IconStyle::Fill),
            _ => None,
        }
    }

    /// Position in `FontRegistry`'s phosphor faces and in the shaping set after the text faces.
    pub fn index(self) -> usize {
        match self {
            IconStyle::Regular => 0,
            IconStyle::Bold => 1,
            IconStyle::Fill => 2,
        }
    }

    fn base(self) -> u32 {
        match self {
            IconStyle::Regular => PUA_BASE,
            IconStyle::Bold => BOLD_BASE,
            IconStyle::Fill => FILL_BASE,
        }
    }
}

/// The font's own codepoint for a named icon, shared by every weight.
pub fn codepoint(name: &str) -> Option<u32> {
    ICON_TABLE.binary_search_by(|(n, _)| (*n).cmp(name)).ok().map(|i| ICON_TABLE[i].1)
}

/// The character to put in a string to draw `name` in `style`.
pub fn glyph(name: &str, style: IconStyle) -> Option<char> {
    let cp = codepoint(name)?;
    char::from_u32(style.base() + (cp - PUA_BASE))
}

/// Every icon name, sorted.
pub fn names() -> impl Iterator<Item = &'static str> {
    ICON_TABLE.iter().map(|(n, _)| *n)
}

/// For a character in one of the three icon ranges: its weight and the codepoint to look up in
/// that weight's font. `None` for any ordinary character.
pub fn decode(ch: char) -> Option<(IconStyle, char)> {
    let c = ch as u32;
    let (style, off) = if (PUA_BASE..PUA_BASE + RANGE_LEN).contains(&c) {
        (IconStyle::Regular, c - PUA_BASE)
    } else if (BOLD_BASE..BOLD_BASE + RANGE_LEN).contains(&c) {
        (IconStyle::Bold, c - BOLD_BASE)
    } else if (FILL_BASE..FILL_BASE + RANGE_LEN).contains(&c) {
        (IconStyle::Fill, c - FILL_BASE)
    } else {
        return None;
    };
    char::from_u32(PUA_BASE + off).map(|font_char| (style, font_char))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn table_is_sorted_and_unique() {
        for pair in ICON_TABLE.windows(2) {
            assert!(pair[0].0 < pair[1].0, "{} then {}", pair[0].0, pair[1].0);
        }
    }

    #[test]
    fn every_codepoint_fits_the_encoded_ranges() {
        for (name, cp) in ICON_TABLE {
            assert!((PUA_BASE..PUA_BASE + RANGE_LEN).contains(cp), "{name} {cp:#x}");
        }
    }

    #[test]
    fn lookup_and_decode_round_trip_for_every_weight() {
        for name in names() {
            for style in IconStyle::ALL {
                let ch = glyph(name, style).unwrap_or_else(|| panic!("no glyph for {name}"));
                let (got_style, font_char) = decode(ch).expect("decodes");
                assert_eq!(got_style, style, "{name}");
                assert_eq!(font_char as u32, codepoint(name).unwrap(), "{name}");
            }
        }
    }

    #[test]
    fn known_names_and_unknown_names() {
        assert_eq!(codepoint("play"), Some(0xE3D0));
        assert_eq!(glyph("play", IconStyle::Regular), Some('\u{E3D0}'));
        assert_eq!(glyph("play", IconStyle::Fill), char::from_u32(FILL_BASE + 0x3D0));
        assert_eq!(codepoint("not-an-icon"), None);
        assert_eq!(decode('a'), None);
        assert_eq!(decode('\u{25B6}'), None);
    }
}
