"""Regenerates src/entropy_gui/icon_table.rs and examples/studio-bundle/src/icon_names.d.ts
from egui-phosphor's variants/codepoints.rs.

    python gen_icons.py <path to codepoints.rs>

The table is (kebab-case Phosphor name, BMP private-use codepoint), sorted by name so the
runtime can binary search it. All Phosphor weights share these codepoints.
"""
import re
import sys

src = open(sys.argv[1], encoding="utf8").read()
rows = {}
for m in re.finditer(r'pub const ([A-Z0-9_]+): &str = "\\u\{([0-9A-Fa-f]+)\}";', src):
    name = m.group(1).lower().replace("_", "-")
    assert name not in rows, name
    rows[name] = int(m.group(2), 16)

out = ["// Generated by src/fonts/phosphor/gen_icons.py from egui-phosphor's variants/codepoints.rs.",
       "// Do not edit by hand. Sorted by name; every Phosphor weight shares these codepoints.",
       "pub const ICON_TABLE: &[(&str, u32)] = &["]
for name in sorted(rows):
    out.append(f'    ("{name}", 0x{rows[name]:04X}),')
out.append("];")
open(r"D:/projects/common/entropy-engine/src/entropy_gui/icon_table.rs", "w", encoding="ascii", newline="\n").write("\n".join(out) + "\n")
names = sorted(rows)
dts = ["// Generated by entropy-engine/src/fonts/phosphor/gen_icons.py. Do not edit by hand.",
       "// Every Phosphor icon name accepted by `Entropy.Icons.get`.",
       "export type IconName ="]
dts += [f'  | "{n}"' for n in names]
dts[-1] += ";"
NL = chr(10)
open(r"D:/projects/common/entropy-engine/examples/studio-bundle/src/icon_names.d.ts", "w", encoding="ascii", newline=NL).write(NL.join(dts) + NL)
print(len(rows), "icons, codepoints", hex(min(rows.values())), "to", hex(max(rows.values())))
